"""Generate stub StatementParser modules under the user data-dir parsers folder.

Scaffold emits the single supported plugin convention::

    def register() -> StatementParser:
        return MyParser()

No bank-specific logic ships here — only a compile-safe stub the user/agent
edits before ``parser_test`` / ``parser_enable``.
"""

from __future__ import annotations

import re
from pathlib import Path

_ID_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

_STUB_TEMPLATE = r'''"""Parser for {institution} ({statement_type}) statements.

Generated by ``canhoto parsers scaffold``. To finish it:

1. See the text this parser receives:
       canhoto parsers preview --file /path/to/statement.pdf
2. Make sniff() recognize the statement, and change _ROW and parse() to
   read its rows.
3. Test, then enable:
       canhoto parsers test --id {parser_id} --file /path/to/statement.pdf
       canhoto parsers enable --id {parser_id}

Rules:
- sniff() returns more than 0 only for markers unique to this statement type.
  Ingest picks the enabled parser with the highest score.
- Build transaction ids from stable data (the bank's operation id, or date,
  amount, and description). Never from the row position: two statements can
  then overwrite each other's rows.
- amount_minor is an integer in minor units: negative for money out, positive
  for money in.
- month is the month the row belongs to. For cards, use the billing month and
  keep the installment (for example "3/10") in the installment field.
- Leave category and kind empty. Canhoto rules and review set them.
"""
from __future__ import annotations

import hashlib
import re
from collections import Counter
from datetime import date
from canhoto.core.models import LedgerTransaction, ParseResult, StatementMeta
from canhoto.core.money import currency_exponent, to_minor

# TODO: set the ISO 4217 code of your statement currency, for example "EUR".
_CURRENCY = "XXX"

# Example row: "2026-06-02  ACME STORE  -12.34". Change it to match your statement.
_ROW = re.compile(r"^(\d{{4}})-(\d{{2}})-(\d{{2}})\s+(.+?)\s+(-?\d+(?:\.\d+)?)$")


class {class_name}:
    """Statement parser: implement sniff and parse before you enable it."""

    id = {parser_id!r}
    statement_type = {statement_type!r}
    institution = {institution!r}
    version = "0.1.0"

    def sniff(self, text: str) -> float:
        """Return 0.0-1.0 confidence that this parser owns the document."""
        # TODO: return a positive score, for example 0.95, when markers unique
        # to this statement appear in text.
        return 0.0

    def parse(self, text: str, source_file: str) -> ParseResult:
        """Return statement metadata and one transaction per row."""
        transactions: list[LedgerTransaction] = []
        seen: Counter[str] = Counter()
        for line in text.splitlines():
            match = _ROW.match(line.strip())
            if match is None:
                continue
            year, month, day, description, amount = match.groups()
            tx_date = date(int(year), int(month), int(day))
            amount_minor = to_minor(amount, _CURRENCY)
            key = f"{{tx_date.isoformat()}}|{{_CURRENCY}}|{{amount_minor}}|{{description}}"
            # Identical rows on one statement get 1, 2, ... in reading order.
            seen[key] += 1
            digest = hashlib.sha256(key.encode()).hexdigest()[:12]
            transactions.append(
                LedgerTransaction(
                    id=f"{{self.id}}-{{digest}}-{{seen[key]}}",
                    date=tx_date,
                    amount_minor=amount_minor,
                    currency=_CURRENCY,
                    amount_exponent=currency_exponent(_CURRENCY),
                    description=description,
                    merchant_raw=description,
                    source_kind=self.statement_type,
                    institution=self.institution,
                    source_file=source_file,
                    month=tx_date.strftime("%Y-%m"),
                    is_expense=amount_minor < 0,
                )
            )
        return ParseResult(
            meta=StatementMeta(
                statement_type=self.statement_type,
                source_file=source_file,
                institution=self.institution,
                currency=_CURRENCY,
            ),
            transactions=transactions,
        )


def register():
    """Required plugin entrypoint: returns a StatementParser instance."""
    return {class_name}()
'''


def validate_parser_id(parser_id: str) -> str:
    """Return ``parser_id`` if it is a safe Python/module identifier."""
    if not parser_id or not _ID_RE.fullmatch(parser_id):
        raise ValueError(
            "parser id must be a Python identifier "
            "(letters, digits, underscore; not starting with a digit)"
        )
    return parser_id


def module_filename(parser_id: str) -> str:
    """Return the default module filename for ``parser_id``."""
    return f"{validate_parser_id(parser_id)}.py"


def class_name_for(parser_id: str) -> str:
    """Derive a CamelCase class name from a snake_case parser id."""
    validate_parser_id(parser_id)
    parts = [p for p in parser_id.split("_") if p]
    base = "".join(p[:1].upper() + p[1:] for p in parts) or "Parser"
    if not base.endswith("Parser"):
        base = f"{base}Parser"
    return base


def render_stub(
    *,
    parser_id: str,
    statement_type: str,
    institution: str,
) -> str:
    """Return source text for a new stub parser module."""
    validate_parser_id(parser_id)
    st = (statement_type or "").strip().lower()
    if st not in {"account", "card"}:
        raise ValueError("statement type must be 'account' or 'card'")
    inst = (institution or "").strip()
    if not inst:
        raise ValueError("institution must be a non-empty string")
    return _STUB_TEMPLATE.format(
        parser_id=parser_id,
        statement_type=st,
        institution=inst,
        class_name=class_name_for(parser_id),
    )


def write_stub_module(
    parsers_dir: Path,
    *,
    parser_id: str,
    statement_type: str,
    institution: str,
    overwrite: bool = False,
) -> Path:
    """Write a stub module under ``parsers_dir`` and return its path."""
    parsers_dir.mkdir(parents=True, exist_ok=True)
    path = (parsers_dir / module_filename(parser_id)).resolve()
    try:
        path.relative_to(parsers_dir.resolve())
    except ValueError as exc:
        raise ValueError(f"parser module path escapes parsers dir: {path}") from exc
    if path.exists() and not overwrite:
        raise FileExistsError(f"parser module already exists: {path.name}")
    path.write_text(
        render_stub(
            parser_id=parser_id,
            statement_type=statement_type,
            institution=institution,
        ),
        encoding="utf-8",
    )
    return path
