"""Generate stub StatementParser modules under the user data-dir parsers folder.

Scaffold emits the single supported plugin convention::

    def register() -> StatementParser:
        return MyParser()

No bank-specific logic ships here — only a compile-safe stub the user/agent
edits before ``parser_test`` / ``parser_enable``.
"""

from __future__ import annotations

import re
from pathlib import Path

_ID_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

_STUB_TEMPLATE = '''\
"""Stub statement parser for {institution} ({statement_type}).

Generated by ``canhoto parsers scaffold``. Edit sniff/parse, then:

    canhoto parsers test --id {parser_id} --file /path/to/sample
    canhoto parsers enable --id {parser_id}

This is not a real bank parser.
"""
from __future__ import annotations

from canhoto.core.models import ParseResult, StatementMeta


class {class_name}:
    """User/plugin parser — implement sniff + parse before enabling."""

    id = {parser_id!r}
    statement_type = {statement_type!r}
    institution = {institution!r}
    version = "0.1.0"

    def sniff(self, text: str) -> float:
        \"\"\"Return 0.0–1.0 confidence that this parser owns the document.\"\"\"
        # TODO: return a positive score when markers unique to this statement appear.
        return 0.0

    def parse(self, text: str, source_file: str) -> ParseResult:
        \"\"\"Return normalized meta + transactions; raise on hard failure.\"\"\"
        # TODO: parse rows into LedgerTransaction instances.
        return ParseResult(
            meta=StatementMeta(
                statement_type=self.statement_type,
                source_file=source_file,
                institution=self.institution,
            ),
            transactions=[],
        )


def register():
    \"\"\"Required plugin entrypoint — returns a StatementParser instance.\"\"\"
    return {class_name}()
'''


def validate_parser_id(parser_id: str) -> str:
    """Return ``parser_id`` if it is a safe Python/module identifier."""
    if not parser_id or not _ID_RE.fullmatch(parser_id):
        raise ValueError(
            "parser id must be a Python identifier "
            "(letters, digits, underscore; not starting with a digit)"
        )
    return parser_id


def module_filename(parser_id: str) -> str:
    """Return the default module filename for ``parser_id``."""
    return f"{validate_parser_id(parser_id)}.py"


def class_name_for(parser_id: str) -> str:
    """Derive a CamelCase class name from a snake_case parser id."""
    validate_parser_id(parser_id)
    parts = [p for p in parser_id.split("_") if p]
    base = "".join(p[:1].upper() + p[1:] for p in parts) or "Parser"
    if not base.endswith("Parser"):
        base = f"{base}Parser"
    return base


def render_stub(
    *,
    parser_id: str,
    statement_type: str,
    institution: str,
) -> str:
    """Return source text for a new stub parser module."""
    validate_parser_id(parser_id)
    st = (statement_type or "").strip().lower()
    if st not in {"account", "card"}:
        raise ValueError("statement type must be 'account' or 'card'")
    inst = (institution or "").strip()
    if not inst:
        raise ValueError("institution must be a non-empty string")
    return _STUB_TEMPLATE.format(
        parser_id=parser_id,
        statement_type=st,
        institution=inst,
        class_name=class_name_for(parser_id),
    )


def write_stub_module(
    parsers_dir: Path,
    *,
    parser_id: str,
    statement_type: str,
    institution: str,
    overwrite: bool = False,
) -> Path:
    """Write a stub module under ``parsers_dir`` and return its path."""
    parsers_dir.mkdir(parents=True, exist_ok=True)
    path = (parsers_dir / module_filename(parser_id)).resolve()
    try:
        path.relative_to(parsers_dir.resolve())
    except ValueError as exc:
        raise ValueError(f"parser module path escapes parsers dir: {path}") from exc
    if path.exists() and not overwrite:
        raise FileExistsError(f"parser module already exists: {path.name}")
    path.write_text(
        render_stub(
            parser_id=parser_id,
            statement_type=statement_type,
            institution=institution,
        ),
        encoding="utf-8",
    )
    return path
